# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'component.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(QtWidgets.QFrame):
    def __init__(self):
        super().__init__()
        self.setObjectName("Frame")
        self.resize(581, 56)
        self.setupUi()

    def setupUi(self):
        self.setStyleSheet("QFrame {\n"
                           "    background-color: rgba(140,4,220,255);\n"
                           "     border: 2px solid white; \n"
                           "}\n"
                           "\n"
                           "QFrame:hover {\n"
                           "    background-color: rgba(140,4,220,200)\n"
                           "}\n"
                           "\n"
                           "QLabel {\n"
                           "    color: white; border: none;\n"
                           "    font-weight: bold;\n"
                           "    font-size: 10pt;\n"
                           "    background-color: transparent\n"
                           "}\n"
                           "\n"
                           "QLabel:hover {\n"
                           "    background-color: transparent\n"
                           "}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "GAMEID"))
        self.label_2.setText(_translate("Frame", "GRADE"))
        self.label_3.setText(_translate("Frame", "TIME"))
        self.label_4.setText(_translate("Frame", "STATS"))


class teste(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        layout = QVBoxLayout()
        for i in range(10):
            layout.addWidget(Ui_Frame())

        widget = QWidget()
        widget.setLayout(layout)

        self.setCentralWidget(widget)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = teste()
    ui.show()
    app.exec()
