# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiAboutScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 499)
        Form.setStyleSheet("#Form {\n"
                           "background-color: transparent;\n"
                           "}")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 700, 500))
        self.frame.setStyleSheet("QFrame#frame {\n"
                                 "    border-image: url(:/images/images/carregamento.png);\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 50, 471, 64))
        self.label.setStyleSheet("color: rgba(100,4,200,255);\n"
                                 "font-size: 35pt;\n"
                                 "font-weight: bold;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(80, 110, 251, 291))
        self.label_2.setStyleSheet("font-weight: bold;\n"
                                   "font-size: 15pt;\n"
                                   "color: white")
        self.label_2.setAlignment(
            QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(390, 130, 261, 251))
        self.label_3.setStyleSheet(
            "border-image: url(:/images/images/wolf.jpg);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.backBtn = QtWidgets.QPushButton(self.frame)
        self.backBtn.setGeometry(QtCore.QRect(10, 10, 31, 23))
        self.backBtn.setStyleSheet("#backBtn {\n"
                                   "    border: none;\n"
                                   "    font-weight: bold\n"
                                   "}\n"
                                   "\n"
                                   "#backBtn:hover {\n"
                                   "    color: rgba(255,255,255,255)\n"
                                   "}")
        self.backBtn.setObjectName("backBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TEAM CHEMYSTERY"))
        self.label_2.setText(_translate("Form", "OBRIGADO!\n"
                                        "O fato de você testar nosso programa nos anima muito, esperamos ver você por aqui mais vezes.\n"
                                        "Lembre-se sempre de se esforçar, pois o lobo sempre te observa!!!"))
        self.backBtn.setText(_translate("Form", ""))


if __name__ == "__main__":
    import sys
    import resAbout_rc
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
