# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiGameScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 500)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 700, 500))
        self.frame.setStyleSheet("#frame {\n"
                                 "border-image: url(:/images/images/carregamento.png);\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(50, 50, 600, 330))
        self.scrollArea.setStyleSheet("QScrollArea {\n"
                                      "    background-color: transparent;\n"
                                      "}\n"
                                      "\n"
                                      "#scrollAreaWidgetContents {\n"
                                      "    background-color: transparent;\n"
                                      "}\n"
                                      "\n"
                                      "")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 581, 328))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(
            self.scrollAreaWidgetContents)
        self.verticalLayout.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 4, 0, 4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.btnClose = QtWidgets.QPushButton(self.frame)
        self.btnClose.setGeometry(QtCore.QRect(660, 10, 30, 30))
        self.btnClose.setStyleSheet("QPushButton#btnClose {\n"
                                    "    border: none;\n"
                                    "    background-color: transparent;\n"
                                    "    color: rgba(255,255,255,255);\n"
                                    "    border-radius: 10px;\n"
                                    "    padding: 10px;\n"
                                    "    font-weight: bold;\n"
                                    "    font-size:10pt\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton#btnClose:hover {\n"
                                    "    background-color: rgba(255,255,255,200);\n"
                                    "    color: rgba(165,4,255,255)\n"
                                    "}")
        self.btnClose.setObjectName("btnClose")
        self.backBtn = QtWidgets.QPushButton(self.frame)
        self.backBtn.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.backBtn.setStyleSheet("QPushButton#backBtn {\n"
                                   "    background-color: transparent;\n"
                                   "    border: none;\n"
                                   "    font-weight: bold;\n"
                                   "    color: white\n"
                                   "}\n"
                                   "")
        self.backBtn.setObjectName("backBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnClose.setText(_translate("Form", "x"))
        self.backBtn.setText(_translate("Form", ""))


if __name__ == "__main__":
    import sys
    import resGames_rc
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
