# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiLoginScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(543, 502)
        Form.setStyleSheet("#Form {\n"
                           "    background: transparent;\n"
                           "}")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 550, 500))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.widget = QtWidgets.QWidget(self.page)
        self.widget.setGeometry(QtCore.QRect(0, 0, 550, 500))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(40, 30, 280, 430))
        self.label.setStyleSheet("background-color: rgba(165,4,255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(270, 30, 240, 430))
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 255);\n"
                                   "border-bottom-right-radius: 50px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(340, 80, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgba(0,0,0,200);")
        self.label_4.setObjectName("label_4")
        self.userText = QtWidgets.QLineEdit(self.widget)
        self.userText.setGeometry(QtCore.QRect(295, 150, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.userText.setFont(font)
        self.userText.setStyleSheet("border: none;\n"
                                    "border-bottom: 2px solid rgba(45,82,101,200);\n"
                                    "color: rgba(0,0,0,240);\n"
                                    "padding-bottom: 7px;")
        self.userText.setObjectName("userText")
        self.passwordText = QtWidgets.QLineEdit(self.widget)
        self.passwordText.setGeometry(QtCore.QRect(295, 215, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.passwordText.setFont(font)
        self.passwordText.setStyleSheet("border: none;\n"
                                        "border-bottom: 2px solid rgba(45,82,101,200);\n"
                                        "color: rgba(0,0,0,240);\n"
                                        "padding-bottom: 7px;")
        self.passwordText.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordText.setObjectName("passwordText")
        self.loginBtn = QtWidgets.QPushButton(self.widget)
        self.loginBtn.setGeometry(QtCore.QRect(295, 295, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.loginBtn.setFont(font)
        self.loginBtn.setStyleSheet("QPushButton#loginBtn {\n"
                                    "    background-color: qlineargradient(spread:pad, x1:0.284091, y1:0.341, x2:0.908727, y2:0.881, stop:0 rgba(165, 4, 255, 255), stop:0.863636 rgba(85, 0, 127, 255));\n"
                                    "    color: rgba(255,255,255,210);\n"
                                    "    border-radius: 5px\n"
                                    "    \n"
                                    "}\n"
                                    "\n"
                                    "QPushButton#loginBtn:hover {    \n"
                                    "    background-color: qlineargradient(spread:pad, x1:0.880682, y1:0.875, x2:0.272364, y2:0.313, stop:0 rgba(165, 4, 255, 255), stop:0.863636 rgba(85, 0, 127, 255));\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton#loginBtn:pressed {\n"
                                    "    padding: 2px 0 0 2px;\n"
                                    "    background-color:  rgba(165,4,255,255);\n"
                                    "    border: 2px solid rgba(165,4,255,255)\n"
                                    "}")
        self.loginBtn.setObjectName("loginBtn")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(295, 341, 191, 16))
        self.label_5.setStyleSheet("color: rgba(0,0,0,210);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(40, 80, 230, 130))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgba(0,0,0,75);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(50, 80, 201, 40))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255,255,255)")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(50, 145, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgba(255,255,255,210);")
        self.label_8.setObjectName("label_8")
        self.close_label = QtWidgets.QLabel(self.widget)
        self.close_label.setGeometry(QtCore.QRect(486, 30, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.close_label.setFont(font)
        self.close_label.setStyleSheet("color: black;\n"
                                       "")
        self.close_label.setObjectName("close_label")
        self.goToRegister = QtWidgets.QPushButton(self.widget)
        self.goToRegister.setGeometry(QtCore.QRect(290, 410, 191, 21))
        self.goToRegister.setStyleSheet("border: none;\n"
                                        "font-size: 11px")
        self.goToRegister.setObjectName("goToRegister")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(105, 350, 100, 100))
        self.label_10.setStyleSheet("image: url(:/images/images/logo 4.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.widget_2 = QtWidgets.QWidget(self.page_2)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 550, 500))
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setGeometry(QtCore.QRect(40, 30, 280, 430))
        self.label_9.setStyleSheet("background-color: rgba(165,4,255, 255);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setGeometry(QtCore.QRect(270, 30, 240, 430))
        self.label_11.setStyleSheet("background-color: rgba(255, 255, 255, 255);\n"
                                    "border-bottom-right-radius: 50px;")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setGeometry(QtCore.QRect(321, 80, 142, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgba(0,0,0,200);")
        self.label_12.setObjectName("label_12")
        self.regUserText = QtWidgets.QLineEdit(self.widget_2)
        self.regUserText.setGeometry(QtCore.QRect(295, 130, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.regUserText.setFont(font)
        self.regUserText.setStyleSheet("background-color: rgba(0,0,0,0);\n"
                                       "border: none;\n"
                                       "border-bottom: 2px solid rgba(45,82,101,200);\n"
                                       "color: rgba(0,0,0,240);\n"
                                       "padding-bottom: 7px;")
        self.regUserText.setObjectName("regUserText")
        self.regPasswordText = QtWidgets.QLineEdit(self.widget_2)
        self.regPasswordText.setGeometry(QtCore.QRect(295, 230, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.regPasswordText.setFont(font)
        self.regPasswordText.setStyleSheet("background-color: rgba(0,0,0,0);\n"
                                           "border: none;\n"
                                           "border-bottom: 2px solid rgba(45,82,101,200);\n"
                                           "color: rgba(0,0,0,240);\n"
                                           "padding-bottom: 7px;")
        self.regPasswordText.setEchoMode(QtWidgets.QLineEdit.Password)
        self.regPasswordText.setObjectName("regPasswordText")
        self.registerBtn = QtWidgets.QPushButton(self.widget_2)
        self.registerBtn.setGeometry(QtCore.QRect(295, 350, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.registerBtn.setFont(font)
        self.registerBtn.setStyleSheet("QPushButton#registerBtn {\n"
                                       "    background-color: qlineargradient(spread:pad, x1:0.284091, y1:0.341, x2:0.908727, y2:0.881, stop:0 rgba(165, 4, 255, 255), stop:0.863636 rgba(85, 0, 127, 255));\n"
                                       "    color: rgba(255,255,255,210);\n"
                                       "    border-radius: 5px\n"
                                       "    \n"
                                       "}\n"
                                       "\n"
                                       "QPushButton#registerBtn:hover {    \n"
                                       "    background-color: qlineargradient(spread:pad, x1:0.880682, y1:0.875, x2:0.272364, y2:0.313, stop:0 rgba(165, 4, 255, 255), stop:0.863636 rgba(85, 0, 127, 255));\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton#registerBtn:pressed {\n"
                                       "    padding: 2px 0 0 2px;\n"
                                       "    background-color:  rgba(165,4,255,255);\n"
                                       "    border: 2px solid rgba(165,4,255,255)\n"
                                       "}")
        self.registerBtn.setObjectName("registerBtn")
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        self.label_14.setGeometry(QtCore.QRect(40, 80, 230, 130))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgba(0,0,0,75);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.widget_2)
        self.label_15.setGeometry(QtCore.QRect(50, 80, 201, 40))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgba(255,255,255,255)")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.widget_2)
        self.label_16.setGeometry(QtCore.QRect(50, 145, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgba(255,255,255,210);")
        self.label_16.setObjectName("label_16")
        self.close_label_2 = QtWidgets.QLabel(self.widget_2)
        self.close_label_2.setGeometry(QtCore.QRect(486, 30, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.close_label_2.setFont(font)
        self.close_label_2.setStyleSheet("color: black;\n"
                                         "")
        self.close_label_2.setObjectName("close_label_2")
        self.regCPasswordtxt = QtWidgets.QLineEdit(self.widget_2)
        self.regCPasswordtxt.setGeometry(QtCore.QRect(295, 280, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.regCPasswordtxt.setFont(font)
        self.regCPasswordtxt.setStyleSheet("background-color: rgba(0,0,0,0);\n"
                                           "border: none;\n"
                                           "border-bottom: 2px solid rgba(45,82,101,200);\n"
                                           "color: rgba(0,0,0,240);\n"
                                           "padding-bottom: 7px;")
        self.regCPasswordtxt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.regCPasswordtxt.setObjectName("regCPasswordtxt")
        self.regEmailTxt = QtWidgets.QLineEdit(self.widget_2)
        self.regEmailTxt.setGeometry(QtCore.QRect(295, 180, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.regEmailTxt.setFont(font)
        self.regEmailTxt.setStyleSheet("background-color: rgba(0,0,0,0);\n"
                                       "border: none;\n"
                                       "border-bottom: 2px solid rgba(45,82,101,200);\n"
                                       "color: rgba(0,0,0,240);\n"
                                       "padding-bottom: 7px;")
        self.regEmailTxt.setText("")
        self.regEmailTxt.setObjectName("regEmailTxt")
        self.goToLogin = QtWidgets.QPushButton(self.widget_2)
        self.goToLogin.setGeometry(QtCore.QRect(350, 410, 75, 23))
        self.goToLogin.setStyleSheet("border:none")
        self.goToLogin.setObjectName("goToLogin")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(105, 350, 100, 100))
        self.label_2.setStyleSheet("image: url(:/images/images/logo 4.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.regUserText, self.regEmailTxt)
        Form.setTabOrder(self.regEmailTxt, self.regPasswordText)
        Form.setTabOrder(self.regPasswordText, self.regCPasswordtxt)
        Form.setTabOrder(self.regCPasswordtxt, self.registerBtn)
        Form.setTabOrder(self.registerBtn, self.loginBtn)
        Form.setTabOrder(self.loginBtn, self.userText)
        Form.setTabOrder(self.userText, self.goToRegister)
        Form.setTabOrder(self.goToRegister, self.passwordText)
        Form.setTabOrder(self.passwordText, self.goToLogin)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "LOGIN"))
        self.userText.setPlaceholderText(_translate("Form", "User Name"))
        self.passwordText.setPlaceholderText(_translate("Form", "Password"))
        self.loginBtn.setText(_translate("Form", "Login"))
        self.label_5.setText(_translate(
            "Form", "<html><head/><body><p align=\"center\">Forgot your username and password?</p></body></html>"))
        self.label_7.setText(_translate("Form", "CHEMYSTERY"))
        self.label_8.setText(_translate("Form", "Hi,\n"
                                        "Welcome to the game!\n"
                                        "Login in your account to start."))
        self.close_label.setText(_translate(
            "Form", "<html><head/><body><p align=\"center\">X</p></body></html>"))
        self.goToRegister.setText(_translate("Form", "Create an account"))
        self.label_12.setText(_translate("Form", "REGISTER"))
        self.regUserText.setPlaceholderText(_translate("Form", "User Name"))
        self.regPasswordText.setPlaceholderText(_translate("Form", "Password"))
        self.registerBtn.setText(_translate("Form", "Register"))
        self.label_15.setText(_translate("Form", "CHEMYSTERY"))
        self.label_16.setText(_translate("Form", "Hi,\n"
                                         "Welcome to the game!\n"
                                         "Login in your account to start."))
        self.close_label_2.setText(_translate(
            "Form", "<html><head/><body><p align=\"center\">X</p></body></html>"))
        self.regCPasswordtxt.setPlaceholderText(
            _translate("Form", "Confirm password"))
        self.regEmailTxt.setPlaceholderText(_translate("Form", "Email"))
        self.goToLogin.setText(_translate("Form", "Go To Login"))


if __name__ == "__main__":
    import sys
    import resLogin_rc

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
