# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiQuizScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(699, 499)
        Form.setStyleSheet("#Form {\n"
                           "background-color: transparent;\n"
                           "}")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 700, 500))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(0, 0, 700, 500))
        self.frame.setStyleSheet("QFrame#frame {        \n"
                                 "    \n"
                                 "    border-image: url(:/images/images/carregamento.png);\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton {\n"
                                 "    font-size: 12pt;\n"
                                 "    font-weight: bold;\n"
                                 "    color: rgba(165, 4, 255, 255);\n"
                                 "    background-color: rgba(255,255,255,255);\n"
                                 "    border-radius: 25.5px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    font-size:13pt;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color: rgba(255,255,255,100)\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lblQuestion = QtWidgets.QLabel(self.frame)
        self.lblQuestion.setGeometry(QtCore.QRect(80, 99, 540, 130))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblQuestion.setFont(font)
        self.lblQuestion.setStyleSheet("background-color: white;\n"
                                       "color: rgba(165, 4, 255, 255);\n"
                                       "padding: 0px 10px;\n"
                                       "font-size:16pt;\n"
                                       "border-radius: 60px;\n"
                                       "font-weight: bold;\n"
                                       "text-align: center;")
        self.lblQuestion.setAlignment(QtCore.Qt.AlignCenter)
        self.lblQuestion.setWordWrap(True)
        self.lblQuestion.setObjectName("lblQuestion")
        self.resposta1 = QtWidgets.QPushButton(self.frame)
        self.resposta1.setGeometry(QtCore.QRect(80, 240, 270, 55))
        self.resposta1.setStyleSheet("")
        self.resposta1.setObjectName("resposta1")
        self.resposta2 = QtWidgets.QPushButton(self.frame)
        self.resposta2.setGeometry(QtCore.QRect(360, 240, 270, 55))
        self.resposta2.setStyleSheet("")
        self.resposta2.setObjectName("resposta2")
        self.resposta3 = QtWidgets.QPushButton(self.frame)
        self.resposta3.setGeometry(QtCore.QRect(80, 310, 270, 55))
        self.resposta3.setStyleSheet("")
        self.resposta3.setObjectName("resposta3")
        self.resposta4 = QtWidgets.QPushButton(self.frame)
        self.resposta4.setGeometry(QtCore.QRect(360, 310, 270, 55))
        self.resposta4.setStyleSheet("")
        self.resposta4.setObjectName("resposta4")
        self.lblTimer = QtWidgets.QLabel(self.frame)
        self.lblTimer.setGeometry(QtCore.QRect(320, 15, 70, 70))
        self.lblTimer.setStyleSheet("#lblTimer {\n"
                                    "font-size: 27pt;\n"
                                    "color: white;\n"
                                    "text-align: center;\n"
                                    "border-radius: 35px;\n"
                                    "border: 2px solid rgba(255,255,255, 255);\n"
                                    "}")
        self.lblTimer.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTimer.setObjectName("lblTimer")
        self.backBtn = QtWidgets.QPushButton(self.frame)
        self.backBtn.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.backBtn.setStyleSheet("QPushButton#backBtn {\n"
                                   "    background-color: transparent;\n"
                                   "    border: none;\n"
                                   "    font-weight: bold;\n"
                                   "    color: white\n"
                                   "}\n"
                                   "")
        self.backBtn.setObjectName("backBtn")
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.frame_3 = QtWidgets.QFrame(self.page_3)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 700, 500))
        self.frame_3.setStyleSheet("QFrame#frame_3 {    \n"
                                   "    border-image: url(:/images/images/carregamento.png);\n"
                                   "}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btnBack = QtWidgets.QPushButton(self.frame_3)
        self.btnBack.setGeometry(QtCore.QRect(210, 320, 300, 50))
        self.btnBack.setStyleSheet("QPushButton#btnBack {\n"
                                   "border: none;\n"
                                   "background-color: white;\n"
                                   "border-radius: 5px;\n"
                                   "padding: 10px;\n"
                                   "font-weight: bold;\n"
                                   "color: rgba(165,4,255, 255);\n"
                                   "font-size:10pt\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton#btnBack:hover {\n"
                                   "    background-color: transparent;\n"
                                   "    color: white;\n"
                                   "    border: 2px solid white\n"
                                   "}")
        self.btnBack.setObjectName("btnBack")
        self.resultlbl = QtWidgets.QLabel(self.frame_3)
        self.resultlbl.setGeometry(QtCore.QRect(260, 70, 200, 200))
        self.resultlbl.setStyleSheet("#resultlbl {\n"
                                     "    font-weight: bold;\n"
                                     "    color: white;\n"
                                     "    font-size: 10pt\n"
                                     "}")
        self.resultlbl.setAlignment(QtCore.Qt.AlignCenter)
        self.resultlbl.setWordWrap(True)
        self.resultlbl.setObjectName("resultlbl")
        self.btnClose = QtWidgets.QPushButton(self.frame_3)
        self.btnClose.setGeometry(QtCore.QRect(660, 10, 30, 30))
        self.btnClose.setStyleSheet("QPushButton#btnClose {\n"
                                    "    border: none;\n"
                                    "    background-color: transparent;\n"
                                    "    color: rgba(255,255,255,255);\n"
                                    "    border-radius: 10px;\n"
                                    "    padding: 10px;\n"
                                    "    font-weight: bold;\n"
                                    "    font-size:10pt\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton#btnClose:hover {\n"
                                    "    background-color: rgba(255,255,255,200);\n"
                                    "    color: rgba(165,4,255,255)\n"
                                    "}")
        self.btnClose.setObjectName("btnClose")
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 700, 500))
        self.frame_2.setStyleSheet("QFrame#frame_2 {\n"
                                   "border-image: url(:/images/images/carregamento.png);\n"
                                   "}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.prepLbl = QtWidgets.QLabel(self.frame_2)
        self.prepLbl.setGeometry(QtCore.QRect(305, 160, 100, 100))
        self.prepLbl.setStyleSheet("font-size: 45pt;\n"
                                   "color: white;\n"
                                   "font-weight: bold;\n"
                                   "border-radius: 50px;\n"
                                   "border: 2px solid white")
        self.prepLbl.setFrameShadow(QtWidgets.QFrame.Plain)
        self.prepLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.prepLbl.setObjectName("prepLbl")
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblQuestion.setText(_translate("Form", "..."))
        self.resposta1.setText(_translate("Form", "..."))
        self.resposta2.setText(_translate("Form", "..."))
        self.resposta3.setText(_translate("Form", "..."))
        self.resposta4.setText(_translate("Form", "..."))
        self.lblTimer.setText(_translate("Form", "40"))
        self.backBtn.setText(_translate("Form", ""))
        self.btnBack.setText(_translate("Form", "VOLTAR PRA TELA INICIAL"))
        self.resultlbl.setText(_translate("Form", "..."))
        self.btnClose.setText(_translate("Form", "x"))
        self.prepLbl.setText(_translate(
            "Form", "<html><head/><body><p align=\"center\">5</p></body></html>"))


if __name__ == "__main__":
    import sys
    import resQuiz_rc
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
