# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiRankScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 500)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 700, 500))
        self.frame.setStyleSheet("QFrame#frame {\n"
                                 "    background-color: white;\n"
                                 "    border: 2px solid black\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "QPushButton#startBtn, #creditsBtn, #rankBtn {\n"
                                 "    font-size: 12pt;\n"
                                 "    padding: 30px 5px;\n"
                                 "    border: solid 1px black;\n"
                                 "    color: white;\n"
                                 "    border-radius: 35px;\n"
                                 "    background-color: qlineargradient(spread:pad, x1:0.670773, y1:0.67, x2:0.0738636, y2:0.051, stop:0 rgba(89, 29, 102, 200), stop:1 rgba(225, 110, 227, 200));\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton#startBtn:hover, #creditsBtn:hover, #rankBtn:hover {\n"
                                 "    background-color: transparent;\n"
                                 "background-color: qlineargradient(spread:pad, x1:0.670773, y1:0.67, x2:0.0738636, y2:0.051, stop:0 rgba(225, 110, 227, 150), stop:1 rgba(89, 29, 102, 150));\n"
                                 "}\n"
                                 "\n"
                                 "QLabel#ranklbl, #gameslbl, #bestlbl {\n"
                                 "background-color: rgba(180,4,255, 255);\n"
                                 "border-radius: 25%;\n"
                                 "border: 5px solid rgba(220,220,220,255);\n"
                                 "color: white;\n"
                                 "font-weight: bold;\n"
                                 "}\n"
                                 "\n"
                                 "QLabel#rank1lbl, #rank2lbl, #rank3lbl, #rank4lbl, #rank5lbl {\n"
                                 "    font-weight: bold;\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnClose = QtWidgets.QPushButton(self.frame)
        self.btnClose.setGeometry(QtCore.QRect(660, 10, 28, 29))
        self.btnClose.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnClose.setStyleSheet("QPushButton#btnClose {\n"
                                    "border: none;\n"
                                    "background-color: transparent;\n"
                                    "color: rgba(150,0,0,120);\n"
                                    "border-radius: 10px;\n"
                                    "font-weight: bold;\n"
                                    "padding: 5px 10px 6px 10px;\n"
                                    "font-size:10pt\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton#btnClose:hover {\n"
                                    "    background-color: rgba(255,0,0,100);\n"
                                    "    color: black\n"
                                    "}")
        self.btnClose.setObjectName("btnClose")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(260, 390, 180, 110))
        self.label.setStyleSheet("image: url(:/images/images/logo5.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(70, 326, 451, 71))
        self.line.setStyleSheet("")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(3)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(100, 290, 75, 70))
        self.label_2.setStyleSheet("background-color: rgba(100,10,220, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(260, 260, 75, 100))
        self.label_3.setStyleSheet("background-color:rgba(165,4,255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(180, 280, 75, 80))
        self.label_4.setStyleSheet("background-color: rgba(130,10,255, 255);;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(420, 160, 75, 200))
        self.label_5.setStyleSheet("background-color: rgba(165,4,255, 255);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(340, 240, 75, 120))
        self.label_6.setStyleSheet("background-color: rgba(130,10,255, 255);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.ranklbl = QtWidgets.QLabel(self.frame)
        self.ranklbl.setGeometry(QtCore.QRect(570, 120, 50, 50))
        self.ranklbl.setStyleSheet("")
        self.ranklbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ranklbl.setObjectName("ranklbl")
        self.bestlbl = QtWidgets.QLabel(self.frame)
        self.bestlbl.setGeometry(QtCore.QRect(570, 180, 50, 50))
        self.bestlbl.setStyleSheet("")
        self.bestlbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bestlbl.setObjectName("bestlbl")
        self.gameslbl = QtWidgets.QLabel(self.frame)
        self.gameslbl.setGeometry(QtCore.QRect(570, 240, 50, 50))
        self.gameslbl.setStyleSheet("")
        self.gameslbl.setAlignment(QtCore.Qt.AlignCenter)
        self.gameslbl.setObjectName("gameslbl")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(550, 135, 20, 20))
        self.label_10.setStyleSheet("font-size: 10pt;\n"
                                    "font-weight: bold;\n"
                                    "color: rgba(180,4,255, 255)")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(550, 195, 20, 20))
        self.label_11.setStyleSheet("font-size: 10pt;\n"
                                    "font-weight: bold;\n"
                                    "color: rgba(180,4,255, 255)")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(550, 255, 20, 20))
        self.label_12.setStyleSheet("font-size: 10pt;\n"
                                    "font-weight: bold;\n"
                                    "color: rgba(180,4,255, 255)")
        self.label_12.setObjectName("label_12")
        self.backBtn = QtWidgets.QPushButton(self.frame)
        self.backBtn.setGeometry(QtCore.QRect(10, 10, 31, 23))
        self.backBtn.setStyleSheet("#backBtn {\n"
                                   "    border: none;\n"
                                   "    font-weight: bold\n"
                                   "}\n"
                                   "\n"
                                   "#backBtn:hover {\n"
                                   "    color: rgba(165,4,255,255)\n"
                                   "}")
        self.backBtn.setObjectName("backBtn")
        self.rank1lbl = QtWidgets.QLabel(self.frame)
        self.rank1lbl.setGeometry(QtCore.QRect(420, 102, 75, 50))
        self.rank1lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.rank1lbl.setWordWrap(True)
        self.rank1lbl.setObjectName("rank1lbl")
        self.rank2lbl = QtWidgets.QLabel(self.frame)
        self.rank2lbl.setGeometry(QtCore.QRect(340, 180, 75, 50))
        self.rank2lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.rank2lbl.setWordWrap(True)
        self.rank2lbl.setObjectName("rank2lbl")
        self.rank3lbl = QtWidgets.QLabel(self.frame)
        self.rank3lbl.setGeometry(QtCore.QRect(260, 200, 75, 50))
        self.rank3lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.rank3lbl.setWordWrap(True)
        self.rank3lbl.setObjectName("rank3lbl")
        self.rank4lbl = QtWidgets.QLabel(self.frame)
        self.rank4lbl.setGeometry(QtCore.QRect(180, 220, 75, 50))
        self.rank4lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.rank4lbl.setWordWrap(True)
        self.rank4lbl.setObjectName("rank4lbl")
        self.rank5lbl = QtWidgets.QLabel(self.frame)
        self.rank5lbl.setGeometry(QtCore.QRect(100, 230, 75, 50))
        self.rank5lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.rank5lbl.setWordWrap(True)
        self.rank5lbl.setObjectName("rank5lbl")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(560, 90, 81, 16))
        self.label_7.setStyleSheet("font-weight: bold")
        self.label_7.setObjectName("label_7")
        self.btnClose.raise_()
        self.line.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.ranklbl.raise_()
        self.bestlbl.raise_()
        self.gameslbl.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.backBtn.raise_()
        self.rank1lbl.raise_()
        self.rank2lbl.raise_()
        self.rank3lbl.raise_()
        self.rank4lbl.raise_()
        self.rank5lbl.raise_()
        self.label_7.raise_()
        self.label.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnClose.setText(_translate("Form", "x"))
        self.ranklbl.setText(_translate("Form", "#150"))
        self.bestlbl.setText(_translate("Form", "7/10"))
        self.gameslbl.setText(_translate("Form", "130"))
        self.label_10.setText(_translate("Form", "►"))
        self.label_11.setText(_translate("Form", "►"))
        self.label_12.setText(_translate("Form", "►"))
        self.backBtn.setText(_translate("Form", ""))
        self.rank1lbl.setText(_translate("Form", "TextLabel"))
        self.rank2lbl.setText(_translate("Form", "TextLabel"))
        self.rank3lbl.setText(_translate("Form", "TextLabel"))
        self.rank4lbl.setText(_translate("Form", "TextLabel"))
        self.rank5lbl.setText(_translate("Form", "TextLabel"))
        self.label_7.setText(_translate("Form", "YOUR STATS"))


if __name__ == "__main__":
    import sys
    import resRank_rc
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
